[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
requires-python = ">=3.12"
[project]
name = "news_events_lib"
version = "0.1.0"
dependencies = [
    "sqlalchemy",
    "pgvector",
    "pydantic"
]
